image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo --baseURL="/2020/labs/lamachinerie/students/alban-petit/"
  artifacts:
    paths:
    - public
  only:
  - master