baseurl: https://albanpetit.com
languageCode: en-us
theme: albanpetit.com-theme
paginate: 5
title: Alban Petit
enableEmoji: true

languages:
    en:
        languageName: English
        weight: 1
        description: Web developer, electronic hobbyist in my free time, here are my personal projects and the content of my training "learn how to make almost anything" from the fab academy
    fr:
        languageName: Francais
        weight: 2
        description: Développeur web, amateur d'électronique à mes heures perdues, voici mes projets personnels et le contenu de ma formation "learn how to make almost anything" de la fab academy
        
DefaultContentLanguage: en

# GA Tracking ID
googleAnalytics: G-ZXXQQEG3J8

permalinks:
    page: /:slug/
    project: /projects/:slug/
    post: /posts/:slug

params:
    mainSections:
        - project
    featuredImageField: image
    rssFullContent: true
    favicon:


    footer:
        since: 2023

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        avatar:
            enabled: true
            local: true
            src: logo.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0
            
    comments:
        enabled: false
        provider: disqus

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            site: Padh_
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: true
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main: []
    
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/AlbanPetit
          params:
            icon: brand-github
            
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/Padh_
          params:
            icon: brand-twitter
        
        - identifier: email
          name: Email
          url: mailto:“contact@albanpetit.com”
          params:
            icon: email

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false