baseurl: /
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Alban Petit

# GA Tracking ID
googleAnalytics:
DefaultContentLanguage: en

permalinks:
    page: /:slug/
    post: /posts/:slug/
    fabacademy: /assignments/:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2022
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        subtitle: IT expert, electronic hobbyist in my free time, here are my personal projects and the content of my training "learn how to make almost anything" from the fab academy
        avatar:
            enabled: false
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

    widgets:
        enabled:
            - search
            - tag-cloud
            - archives

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            site: Padh_
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: true
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: assignments
          name: Fabacademy
          url: /assignments
          weight: -100
          params:
              newTab: false
              icon: book

        - identifier: posts
          name: Blog posts
          url: /
          weight: -100
          params:
              newTab: false
              icon: home
    
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/AlbanPetit
          params:
            icon: brand-github
            
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/Padh_
          params:
            icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false