baseurl: https://albanpetit.com
languageCode: en-us
theme: albanpetit.com-theme
paginate: 5
title: Alban Petit
enableEmoji: true

languages:
  en:
    languageName: English
    weight: 1
    description: Hi I'm Alban, here is my personal website where I share my projects on various topics, including electronics, web development, and a lot of things related to the Maker world. Some tutorials, experiences, and information are also available in the blog posts section.
  fr:
    languageName: Francais
    weight: 2
    description: Salut, je suis Alban. Voici mon site personnel où je partage mes projets sur divers sujets, notamment l'électronique, le développement web, et beaucoup de choses liées au monde des Makers. Certains tutoriels, retours d'expérience et informations sont également disponibles dans la section "Articles".

DefaultContentLanguage: en

# GA Tracking ID
googleAnalytics: GTM-PTW3KSCP

permalinks:
  page: /:slug/
  post: /posts/:slug

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon:

  footer:
    since: 2023

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    avatar:
      enabled: true
      local: true
      src: logo.png

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: "albanpetit/albanpetit.com"
      repoID: "MDEwOlJlcG9zaXRvcnkzOTY5MDM1OTc="
      category: "Website comments"
      categoryID: "DIC_kwDOF6hErc4CeFTI"
      mapping: "pathname"
      lightTheme: "https://albanpetit.com/giscus-light.css"
      darkTheme: "https://albanpetit.com/giscus-dark.css"
      reactionsEnabled: 1
      emitMetadata: 0

  widgets:
    homepage:
      - type: search
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
      - type: archives
        params:
          limit: 5

    page:
      - type: toc

  opengraph:
    twitter:
      site: Padh_
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    toggle: true
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  main: []

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
